# Generated by Django 6.0 on 2025-12-07 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g., v1.0.0', max_length=20, unique=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(help_text='Summary of changes in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Version',
                'verbose_name_plural': 'API Versions',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='SetupGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guide_type', models.CharField(choices=[('installation', 'Installation'), ('configuration', 'Configuration'), ('deployment', 'Deployment'), ('troubleshooting', 'Troubleshooting')], max_length=20)),
                ('content', models.TextField(help_text='Markdown supported')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setup Guide',
                'verbose_name_plural': 'Setup Guides',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='APIChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('feature', 'New Feature'), ('enhancement', 'Enhancement'), ('bugfix', 'Bug Fix'), ('breaking', 'Breaking Change'), ('deprecation', 'Deprecation')], max_length=20)),
                ('app_name', models.CharField(help_text='e.g., products, orders', max_length=50)),
                ('endpoint', models.CharField(help_text='e.g., /products/api/', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='documentation.apiversion')),
            ],
            options={
                'verbose_name': 'API Change',
                'verbose_name_plural': 'API Changes',
                'ordering': ['-created_at'],
            },
        ),
    ]
